version: '3.9'
services:
  linebot_server:
    container_name: linebot_server
    build:
      context: .
      dockerfile: docker/Dockerfile
    entrypoint: cargo run
    ports: 
      - "8000:8000"
    networks:
      - linebot

networks:
  linebot:
    name: linebot
    driver: bridge